<?php

namespace App\Action\Commend;

use Mx\Helper\Page;
use Mx\Http\ActionAbstract;

/**
 * Class GetNews
 * @package App\Action\Commend
 *
 * 接受用户的get请求并且按默认每次返回10条新闻数据
 */
class GetNews extends ActionAbstract
{
    protected function handleGet()
    {
        // TODO: Change the autogenerated stub
        $news = $this->service('Commend\GetNews');
        $result = $news->run();
        $url = $this->config('realUrl') . 'news?';
        $result['url'] = $url;
        $this->response($result);
        $this->code(200);
    }
}